export enum ActionType {
  DARK_MODE_ON = 'DARK_MODE_ON',
  DARK_MODE_OFF = 'DARK_MODE_OFF',
  MENU_ON = 'MENU_ON',
  MENU_OFF = 'MENU_OFF',
  ADD_DOCUMENT = 'ADD_DOCUMENT',
  DELETE_DOCUMENT = 'DELETE_DOCUMENT',
  OPEN_PREVIEW = 'OPEN_PREVIEW',
  CLOSE_PREVIEW = 'CLOSE_PREVIEW',
  SELECT_DOCUMENT_ID = 'SELECT_DOCUMENT_ID',
  UPDATE_DOCUMENT_TITLE = 'UPDATE_DOCUMENT_TITLE',
  ADD_DOCUMENTS = 'ADD_DOCUMENTS',
}
