export enum ActionType {
  DARK_MODE_ON = 'DARK_MODE_ON',
  DARK_MODE_OFF = 'DARK_MODE_OFF',
  MENU_ON = 'MENU_ON',
  MENU_OFF = 'MENU_OFF',
  ADD_DOCUMENT = 'ADD_DOCUMENT',
  DELETE_DOCUMENT = 'DELETE_DOCUMENT',
}
